spring:
  application:
    name: brendystudy_spring_backend

  datasource:
    url: jdbc:mysql://localhost:3306/brendystudy_spring
    username: root
    password: '699182120'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080